server:
  port: 8080
spring:
  application:
    name: welcome-service
  config:
    import: optional:configserver:http://localhost:8888/
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS
