server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/william-carvalho/config-server-2025
          search-paths: 'welcome-service*'
#          username: admin
#          password: admin
#           deafault-label: main

#  profiles:
#    active:
#      - native
